-- Migration to add appointment_reminder_log table
CREATE TABLE IF NOT EXISTS "appointment_reminder_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "appointment_reminder_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_name" varchar(255) NOT NULL,
	"phone_number" varchar(20) NOT NULL,
	"appointment_date" varchar(20) NOT NULL,
	"time_slot" varchar(100) NOT NULL,
	"app" varchar(100) NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"api_response" json,
	"error_message" text,
	"workspace_id" varchar(255) NOT NULL,
	"channel_id" varchar(255) NOT NULL,
	"project_id" varchar(255) NOT NULL,
	"sent_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"sent_by" varchar(256)
);

-- Create indexes for the appointment_reminder_log table
CREATE INDEX IF NOT EXISTS "reminder_phone_idx" ON "appointment_reminder_log" USING btree ("phone_number");
CREATE INDEX IF NOT EXISTS "reminder_date_idx" ON "appointment_reminder_log" USING btree ("appointment_date");
CREATE INDEX IF NOT EXISTS "reminder_app_idx" ON "appointment_reminder_log" USING btree ("app");
CREATE INDEX IF NOT EXISTS "reminder_sent_at_idx" ON "appointment_reminder_log" USING btree ("sent_at");
CREATE INDEX IF NOT EXISTS "reminder_status_idx" ON "appointment_reminder_log" USING btree ("status"); 