-- Migration: Update playbook schema for multiple agents and filtering
-- This migration adds support for multiple agents per playbook and filtering criteria

-- First, create the new playbook_agents junction table
CREATE TABLE "t3gallery_playbook_agents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3gallery_playbook_agents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playbook_id" integer NOT NULL,
	"agent_id" varchar(256) NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"assigned_by" varchar(256),
	"is_primary" boolean DEFAULT false,
	CONSTRAINT "t3gallery_playbook_agents_playbook_id_fkey" FOREIGN KEY ("playbook_id") REFERENCES "t3gallery_playbooks"("id") ON DELETE CASCADE,
	CONSTRAINT "t3gallery_playbook_agents_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "t3gallery_users"("id") ON DELETE CASCADE,
	CONSTRAINT "t3gallery_playbook_agents_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "t3gallery_users"("id")
);

-- Create indexes for the new table
CREATE INDEX "playbook_agents_playbook_idx" ON "t3gallery_playbook_agents" ("playbook_id");
CREATE INDEX "playbook_agents_agent_idx" ON "t3gallery_playbook_agents" ("agent_id");
CREATE UNIQUE INDEX "playbook_agents_unique_idx" ON "t3gallery_playbook_agents" ("playbook_id", "agent_id");

-- Add new columns to the existing playbooks table
ALTER TABLE "t3gallery_playbooks" 
ADD COLUMN "description" text,
ADD COLUMN "created_by" varchar(256) REFERENCES "t3gallery_users"("id"),
ADD COLUMN "filter_status" json,
ADD COLUMN "filter_assigned_to" json,
ADD COLUMN "filter_include_unassigned" boolean DEFAULT false,
ADD COLUMN "filter_sources" json,
ADD COLUMN "filter_employment_statuses" json,
ADD COLUMN "filter_loan_purposes" json,
ADD COLUMN "filter_residential_statuses" json,
ADD COLUMN "filter_lead_types" json,
ADD COLUMN "filter_eligibility_statuses" json,
ADD COLUMN "filter_amount_min" integer,
ADD COLUMN "filter_amount_max" integer,
ADD COLUMN "filter_date_from" varchar(20),
ADD COLUMN "filter_date_to" varchar(20),
ADD COLUMN "filter_follow_up_date_from" varchar(20),
ADD COLUMN "filter_follow_up_date_to" varchar(20),
ADD COLUMN "filter_assigned_in_last_days" integer,
ADD COLUMN "call_script" text,
ADD COLUMN "timeset_id" varchar(255),
ADD COLUMN "team_id" varchar(255),
ADD COLUMN "auto_sync_enabled" boolean DEFAULT true,
ADD COLUMN "sync_frequency" varchar(50) DEFAULT 'daily';

-- Create indexes for the new filter columns
CREATE INDEX "playbooks_created_by_idx" ON "t3gallery_playbooks" ("created_by");
CREATE INDEX "playbooks_active_idx" ON "t3gallery_playbooks" ("is_active");

-- Migrate existing data: for each existing playbook, create a playbook_agent record
-- and set the created_by to the agent_id
INSERT INTO "t3gallery_playbook_agents" ("playbook_id", "agent_id", "assigned_at", "is_primary")
SELECT id, agent_id, created_at, true
FROM "t3gallery_playbooks"
WHERE agent_id IS NOT NULL;

-- Update created_by for existing playbooks
UPDATE "t3gallery_playbooks" 
SET created_by = agent_id 
WHERE created_by IS NULL AND agent_id IS NOT NULL;

-- Remove the old agent_id column (after ensuring data is migrated)
ALTER TABLE "t3gallery_playbooks" DROP COLUMN "agent_id";
