name: Auto-merge Environment Promotion

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' && 
      startsWith(github.event.pull_request.title, 'Promote')
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"